-- Table: public.person

-- DROP TABLE IF EXISTS public.person;

CREATE TABLE IF NOT EXISTS public.person
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    personal_number character varying(12)[] COLLATE pg_catalog."default" NOT NULL,
    name character varying(500)[] COLLATE pg_catalog."default" NOT NULL,
    address character varying(500)[] COLLATE pg_catalog."default" NOT NULL,
    phone_number character varying(50)[] COLLATE pg_catalog."default" NOT NULL,
    mail_address character varying(50)[] COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT person_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.person
    OWNER to postgres;